### tesnsor: multi-dimensional arrays of numbers that represent complex data.
### whenever we have input data in any format we need to convert it intfo a tensor which will contain numbers.
### then these tensors are passed to the neural netwrok for the model.


In [1]:
# import libraries
import torch
import pandas as pd 
import numpy as np

In [2]:
# create a simple tensor with torch
scalar=torch.tensor(8)
type(scalar), scalar

(torch.Tensor, tensor(8))

In [3]:
# to check the number of dimensions 
scalar.ndim

0

In [4]:
# to get back the tensro  or value as an integer
scalar.item()

8

In [5]:
# create a vector or list
vector=torch.tensor([8,7]) # this is the one dimensional vector

# print the data
vector, type(vector), vector.ndim, vector.shape

(tensor([8, 7]), torch.Tensor, 1, torch.Size([2]))

In [6]:
# create a matrix
matrix=torch.Tensor([[8,7], [9,2]])

# print
matrix, type(matrix), matrix.ndim, matrix.shape, matrix[0][1]

(tensor([[8., 7.],
         [9., 2.]]),
 torch.Tensor,
 2,
 torch.Size([2, 2]),
 tensor(7.))

In [7]:
# create a tensor of more than 2 dimensions
tens=torch.tensor([[[1,2,3], [4,5,6], [8,5,2]]])

# print
tens, type(tens), tens.ndim, tens.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [8, 5, 2]]]),
 torch.Tensor,
 3,
 torch.Size([1, 3, 3]))

### result: from the above tensor.size([1,3,3]) the first 1 shows the first bracket of the tensor, the second 3 shows the second bracket which contains total three more rows and the 3rd 3 shows the number of columns 

## random tensors:
### theese are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [8]:
# create a random tensor
r_tens=torch.rand(3, 4) # randopm tensor of size 3*4
# we can give as many dimensions as we need such as (1,4,5)

r_tens, type(r_tens), r_tens.shape, r_tens.ndim

(tensor([[0.8404, 0.9114, 0.6551, 0.5017],
         [0.6070, 0.1399, 0.0846, 0.4011],
         [0.7461, 0.8456, 0.4632, 0.0856]]),
 torch.Tensor,
 torch.Size([3, 4]),
 2)

In [9]:
# random tensor of the similar size of an image 
random_tens_image=torch.rand(size=(224, 224, 3))
# here we have height, width and colour channel(Red, green, blue)
# color channel can also come first as (3, 224, 224)
  
random_tens_image.shape, random_tens_image.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones tensors

In [10]:
# zeros
z_tens=torch.zeros(size=(3, 5))

# print
z_tens, z_tens.shape, z_tens.ndim

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.Size([3, 5]),
 2)

In [11]:
# ones
o_tens=torch.ones(size=(3, 5))

# print
o_tens, o_tens.shape, o_tens.ndim

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.Size([3, 5]),
 2)

## create tensors using arange

In [12]:
# tesnor using arange
range_tens=torch.arange(1, 5)# 1*5 tensor, one dimensional

# print
range_tens, range_tens.shape, range_tens.ndim

(tensor([1, 2, 3, 4]), torch.Size([4]), 1)

In [13]:
# using step
step_range_tens=torch.arange(start=0, end=500, step=50)

# print
step_range_tens, step_range_tens.shape, step_range_tens.ndim

(tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450]),
 torch.Size([10]),
 1)

In [14]:
# to check on which device we are currently working
step_range_tens.device

device(type='cpu')

## Maths on tensors

In [15]:
# adding to each element
tens=torch.Tensor([3, 5, 7])

# add 100 to each tensor
after_add=tens + 100

# multiply by 2
after_mul=tens*2

# divide by 2
after_div=tens/2

# subtract 1
after_sub=tens-1

# print the values
after_add, after_mul, after_div, after_sub

(tensor([103., 105., 107.]),
 tensor([ 6., 10., 14.]),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([2., 4., 6.]))

In [16]:
# performing maths using pytorch as follows
after_add=torch.add(tens, 100)

# mul
after_mul=torch.mul(tens, 2)

# div
after_div=torch.div(tens, 2)

# sub
after_sub=torch.sub(tens, 1)

# print the values 
after_add, after_mul, after_div, after_sub

(tensor([103., 105., 107.]),
 tensor([ 6., 10., 14.]),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([2., 4., 6.]))

## Matrix multiplication:
### by element wise mul
### by matrix mul as follows

In [17]:
# making use of the previous tens
print(tens, "*", tens)

# now element-wise mul
print(tens*tens)

tensor([3., 5., 7.]) * tensor([3., 5., 7.])
tensor([ 9., 25., 49.])


In [18]:
# using matmul method that performs the dotf product between two matrices and returns a scalar
mul=torch.matmul(tens, tens) 
# we can also write mm in place of matmul
mul

tensor(83.)

### result: manually --> 3* 3 + 5* 5 + 7*7 = 83

In [19]:
# shape miss-match issues
tens1=torch.tensor([[1,2], [5,6], [8,9]])
tens2=torch.Tensor([[2,1], [5,7], [5, 8]])

# matmul
result=torch.mm(tens1, tens2)
result

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### above error is caused by the miss match of the shape because both of the tensors are f the shape 3*2 and for multiplication we have to satisfy that columns of the first matrix must be equal to the rows of the second. and this condition is violated here

### To avoid above problem let's apply transpose of a matrix method as follows

In [20]:
# transposing the tensor
tens1=tens1.float() # dtype change
t_tens1=tens1.T
# now multiply
result=torch.mm(t_tens1, tens2)
result, result.shape
# t_tens1.shape, tens2.shape

(tensor([[ 67., 100.],
         [ 79., 116.]]),
 torch.Size([2, 2]))

## min, max, mean, sum etc

In [21]:
# random tensor
rn=torch.arange(10, 200, 10).float()# step of 10

# above mentioned operations
print('the min is ', torch.min(rn), "\t max ", torch.max(rn), "\t sum ", torch.sum(rn), "\t mean ", torch.mean(rn))

the min is  tensor(10.) 	 max  tensor(190.) 	 sum  tensor(1900.) 	 mean  tensor(100.)


In [22]:
# find the values according to their index/ position
# we make use of argmin method for min
print('the min is at ', rn.argmin(), "\t max at ", rn.argmax())

the min is at  tensor(0) 	 max at  tensor(18)


In [23]:
# check the min at 0 and max qat 18
print("min ", rn[0], " max ", rn[18])

min  tensor(10.)  max  tensor(190.)
